### ISSUE TITLE
Capstone2 kanban board setup

### ISSUE THREAD

**Issue by wayungi** [karlavdelgadof/Capstone-M2-JS#21]
#### Here you can find the link to our kanban board
- [Our board](https://github.com/karlavdelgadof/Capstone-M2-JS/projects/1)
#### Contributors
- Hi there, this is our team
- @karlavdelgadof  student A
- @wayungi  student B

**Comment by CollinsTatang** [comment]
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by karlavdelgadof** [comment]
Thanks for ur feedback! @CollinsTatang :100:
